// Generated by Wrangler on Thu Jul 11 2024 18:01:57 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	SYNC_SERVER_DO: DurableObjectNamespace;
	AUTOMERGE: R2Bucket;
	MEDIA: R2Bucket;
}
